spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/testing_service?characterEncoding=UTF-8&amp&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    "[org.hibernate]" : DEBUG


server:
  port: 8081




